import type { RegisteredToolInput } from '@/services/runtime/tools/tool-types';
import {
  DEFAULT_EXTERNAL_APPROVAL,
  DEFAULT_READ_APPROVAL,
  DEFAULT_READ_RETRY_POLICY,
  DEFAULT_WRITE_RETRY_POLICY,
} from '@/services/runtime/tools/tool-types';

const externalPermissions = {
  requiredFlags: ['can_use_media_tools'],
  categoryDefault: true,
};

export const mediaTools: RegisteredToolInput[] = [
  {
    id: 'media.product_ad.generate',
    name: 'Generate Product Ad',
    description: 'Create a cinematic product ad video from one or more product reference images.',
    version: '1.0.0',
    category: 'media',
    permissions: externalPermissions,
    approvalPolicy: {
      ...DEFAULT_EXTERNAL_APPROVAL,
      reason: 'Product ad generation may consume paid credits and requires explicit approval.',
    },
    timeoutMs: 30_000,
    retryPolicy: DEFAULT_WRITE_RETRY_POLICY,
    inputSchema: {
      type: 'object',
      properties: {
        product_images: {
          type: 'array',
          items: { type: 'string' },
          minItems: 1,
          maxItems: 10,
        },
        product_info: { type: 'string', minLength: 1, maxLength: 3000 },
        concept: { type: 'string', minLength: 1, maxLength: 5000 },
        duration: { type: 'number', minimum: 4, maximum: 15 },
      },
      required: ['product_images', 'product_info', 'concept'],
      additionalProperties: false,
    },
    outputSchema: {
      type: 'object',
      properties: {
        taskId: { type: 'string' },
        status: { type: 'string' },
        kind: { type: 'string' },
      },
      required: ['taskId', 'status', 'kind'],
    },
    enabled: true,
  },
  {
    id: 'media.ad_localization.generate',
    name: 'Localize Ad Image',
    description: 'Localize on-image ad text while preserving the original creative and layout.',
    version: '1.0.0',
    category: 'media',
    permissions: externalPermissions,
    approvalPolicy: {
      ...DEFAULT_EXTERNAL_APPROVAL,
      reason: 'Ad localization may consume paid credits and requires explicit approval.',
    },
    timeoutMs: 30_000,
    retryPolicy: DEFAULT_WRITE_RETRY_POLICY,
    inputSchema: {
      type: 'object',
      properties: {
        reference_image: { type: 'string', minLength: 1 },
        target_language: { type: 'string', minLength: 2, maxLength: 12 },
      },
      required: ['reference_image', 'target_language'],
      additionalProperties: false,
    },
    outputSchema: {
      type: 'object',
      properties: {
        taskId: { type: 'string' },
        status: { type: 'string' },
        kind: { type: 'string' },
      },
      required: ['taskId', 'status', 'kind'],
    },
    enabled: true,
  },
  {
    id: 'media.product_campaign.generate',
    name: 'Generate Product Campaign Images',
    description: 'Create a campaign image set from a product reference and a creative brief.',
    version: '1.0.0',
    category: 'media',
    permissions: externalPermissions,
    approvalPolicy: {
      ...DEFAULT_EXTERNAL_APPROVAL,
      reason: 'Campaign image generation may consume paid credits and requires explicit approval.',
    },
    timeoutMs: 30_000,
    retryPolicy: DEFAULT_WRITE_RETRY_POLICY,
    inputSchema: {
      type: 'object',
      properties: {
        image: { type: 'string', minLength: 1 },
        prompt: { type: 'string', minLength: 1, maxLength: 5000 },
      },
      required: ['image', 'prompt'],
      additionalProperties: false,
    },
    outputSchema: {
      type: 'object',
      properties: {
        taskId: { type: 'string' },
        status: { type: 'string' },
        kind: { type: 'string' },
      },
      required: ['taskId', 'status', 'kind'],
    },
    enabled: true,
  },
  {
    id: 'media.multi_shot.generate',
    name: 'Generate Multi-Shot Video',
    description: 'Create a multi-shot video from a sequence of shot prompts and durations.',
    version: '1.0.0',
    category: 'media',
    permissions: externalPermissions,
    approvalPolicy: {
      ...DEFAULT_EXTERNAL_APPROVAL,
      reason: 'Multi-shot video generation may consume paid credits and requires explicit approval.',
    },
    timeoutMs: 30_000,
    retryPolicy: DEFAULT_WRITE_RETRY_POLICY,
    inputSchema: {
      type: 'object',
      properties: {
        ratio: { type: 'string' },
        shots: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              prompt: { type: 'string', minLength: 1, maxLength: 1500 },
              duration: { type: 'number', minimum: 1, maximum: 15 },
            },
            required: ['prompt', 'duration'],
            additionalProperties: false,
          },
          minItems: 2,
          maxItems: 8,
        },
      },
      required: ['shots'],
      additionalProperties: false,
    },
    outputSchema: {
      type: 'object',
      properties: {
        taskId: { type: 'string' },
        status: { type: 'string' },
        kind: { type: 'string' },
      },
      required: ['taskId', 'status', 'kind'],
    },
    enabled: true,
  },
  {
    id: 'media.product_ugc.generate',
    name: 'Generate Product UGC',
    description: 'Create a UGC-style product ad video from a creator image, product image and concept.',
    version: '1.0.0',
    category: 'media',
    permissions: externalPermissions,
    approvalPolicy: {
      ...DEFAULT_EXTERNAL_APPROVAL,
      reason: 'Product UGC generation may consume paid credits and requires explicit approval.',
    },
    timeoutMs: 30_000,
    retryPolicy: DEFAULT_WRITE_RETRY_POLICY,
    inputSchema: {
      type: 'object',
      properties: {
        character_image: { type: 'string', minLength: 1 },
        product_image: { type: 'string', minLength: 1 },
        product_info: { type: 'string', minLength: 1, maxLength: 3000 },
        concept: { type: 'string', minLength: 1, maxLength: 5000 },
        duration: { type: 'number', minimum: 5, maximum: 30 },
      },
      required: ['character_image', 'product_image', 'product_info', 'concept'],
      additionalProperties: false,
    },
    outputSchema: {
      type: 'object',
      properties: {
        taskId: { type: 'string' },
        status: { type: 'string' },
        kind: { type: 'string' },
      },
      required: ['taskId', 'status', 'kind'],
    },
    enabled: true,
  },
  {
    id: 'media.video.generate',
    name: 'Generate Video',
    description: 'Start a paid video generation job from text and an optional reference image.',
    version: '1.0.0',
    category: 'media',
    permissions: externalPermissions,
    approvalPolicy: {
      ...DEFAULT_EXTERNAL_APPROVAL,
      reason: 'Video generation may consume paid credits and requires explicit approval.',
    },
    timeoutMs: 30_000,
    retryPolicy: DEFAULT_WRITE_RETRY_POLICY,
    inputSchema: {
      type: 'object',
      properties: {
        prompt_text: { type: 'string', minLength: 1, maxLength: 5000 },
        image_url: { type: 'string' },
        model: { type: 'string' },
        ratio: { type: 'string' },
        duration: { type: 'number', minimum: 4, maximum: 30 },
      },
      required: ['prompt_text'],
      additionalProperties: false,
    },
    outputSchema: {
      type: 'object',
      properties: {
        taskId: { type: 'string' },
        status: { type: 'string' },
        kind: { type: 'string' },
      },
      required: ['taskId', 'status', 'kind'],
    },
    enabled: true,
  },
  {
    id: 'media.image.generate',
    name: 'Generate Image',
    description: 'Start a paid image generation job for a scene, storyboard frame, creative or still.',
    version: '1.0.0',
    category: 'media',
    permissions: externalPermissions,
    approvalPolicy: {
      ...DEFAULT_EXTERNAL_APPROVAL,
      reason: 'Image generation may consume paid credits and requires explicit approval.',
    },
    timeoutMs: 30_000,
    retryPolicy: DEFAULT_WRITE_RETRY_POLICY,
    inputSchema: {
      type: 'object',
      properties: {
        prompt_text: { type: 'string', minLength: 1, maxLength: 32000 },
        model: { type: 'string' },
        ratio: { type: 'string' },
        output_count: { type: 'number', minimum: 1, maximum: 4 },
        reference_images: {
          type: 'array',
          items: { type: 'string' },
          maxItems: 3,
        },
      },
      required: ['prompt_text'],
      additionalProperties: false,
    },
    outputSchema: {
      type: 'object',
      properties: {
        taskId: { type: 'string' },
        status: { type: 'string' },
        kind: { type: 'string' },
      },
      required: ['taskId', 'status', 'kind'],
    },
    enabled: true,
  },
  {
    id: 'media.image.upscale',
    name: 'Upscale Image',
    description: 'Increase image resolution while preserving the original composition.',
    version: '1.0.0',
    category: 'media',
    permissions: externalPermissions,
    approvalPolicy: {
      ...DEFAULT_EXTERNAL_APPROVAL,
      reason: 'Image upscaling may consume paid credits and requires explicit approval.',
    },
    timeoutMs: 30_000,
    retryPolicy: DEFAULT_WRITE_RETRY_POLICY,
    inputSchema: {
      type: 'object',
      properties: {
        image: { type: 'string', minLength: 1 },
        scale_factor: { type: 'number', enum: [2, 4, 8, 16] },
        flavor: { type: 'string', enum: ['sublime', 'photo', 'photo_denoiser'] },
        sharpen: { type: 'number', minimum: 0, maximum: 100 },
        smart_grain: { type: 'number', minimum: 0, maximum: 100 },
        ultra_detail: { type: 'number', minimum: 0, maximum: 100 },
      },
      required: ['image'],
      additionalProperties: false,
    },
    outputSchema: {
      type: 'object',
      properties: {
        taskId: { type: 'string' },
        status: { type: 'string' },
        kind: { type: 'string' },
      },
      required: ['taskId', 'status', 'kind'],
    },
    enabled: true,
  },
  {
    id: 'media.video.upscale',
    name: 'Upscale Video',
    description: 'Increase video resolution up to 4K while preserving the original content.',
    version: '1.0.0',
    category: 'media',
    permissions: externalPermissions,
    approvalPolicy: {
      ...DEFAULT_EXTERNAL_APPROVAL,
      reason: 'Video upscaling may consume a significant number of paid credits and requires explicit approval.',
    },
    timeoutMs: 30_000,
    retryPolicy: DEFAULT_WRITE_RETRY_POLICY,
    inputSchema: {
      type: 'object',
      properties: {
        video: { type: 'string', minLength: 1 },
        resolution: { type: 'string', enum: ['720p', '1k', '2k', '4k'] },
        creativity: { type: 'number', minimum: 0, maximum: 100 },
        sharpen: { type: 'number', minimum: 0, maximum: 100 },
        smart_grain: { type: 'number', minimum: 0, maximum: 100 },
        flavor: { type: 'string' },
        fps_boost: { type: 'boolean' },
      },
      required: ['video'],
      additionalProperties: false,
    },
    outputSchema: {
      type: 'object',
      properties: {
        taskId: { type: 'string' },
        status: { type: 'string' },
        kind: { type: 'string' },
      },
      required: ['taskId', 'status', 'kind'],
    },
    enabled: true,
  },
  {
    id: 'media.sound_effect.generate',
    name: 'Generate Sound Effect',
    description: 'Generate a sound effect or ambience from a text description.',
    version: '1.0.0',
    category: 'media',
    permissions: externalPermissions,
    approvalPolicy: {
      ...DEFAULT_EXTERNAL_APPROVAL,
      reason: 'Sound effect generation may consume paid credits and requires explicit approval.',
    },
    timeoutMs: 30_000,
    retryPolicy: DEFAULT_WRITE_RETRY_POLICY,
    inputSchema: {
      type: 'object',
      properties: {
        prompt_text: { type: 'string', minLength: 1, maxLength: 450 },
        duration: { type: 'number', minimum: 0.5, maximum: 30 },
        loop: { type: 'boolean' },
      },
      required: ['prompt_text'],
      additionalProperties: false,
    },
    outputSchema: {
      type: 'object',
      properties: {
        taskId: { type: 'string' },
        status: { type: 'string' },
        kind: { type: 'string' },
      },
      required: ['taskId', 'status', 'kind'],
    },
    enabled: true,
  },
  {
    id: 'media.video.edit',
    name: 'Edit Video',
    description: 'Apply a targeted edit to an existing video.',
    version: '1.0.0',
    category: 'media',
    permissions: externalPermissions,
    approvalPolicy: {
      ...DEFAULT_EXTERNAL_APPROVAL,
      reason: 'Video editing may consume paid credits and requires explicit approval.',
    },
    timeoutMs: 30000,
    retryPolicy: DEFAULT_WRITE_RETRY_POLICY,
    inputSchema: {
      type: 'object',
      properties: {
        video_uri: { type: 'string', minLength: 1 },
        prompt_text: { type: 'string', minLength: 1, maxLength: 5000 },
      },
      required: ['video_uri', 'prompt_text'],
      additionalProperties: false,
    },
    outputSchema: {
      type: 'object',
      properties: {
        taskId: { type: 'string' },
        status: { type: 'string' },
        kind: { type: 'string' },
      },
      required: ['taskId','status','kind'],
    },
    enabled: true,
  },
  {
    id: 'media.video.expand',
    name: 'Expand Video Frame',
    description: 'Expand a video to a new aspect ratio without cropping.',
    version: '1.0.0',
    category: 'media',
    permissions: externalPermissions,
    approvalPolicy: {
      ...DEFAULT_EXTERNAL_APPROVAL,
      reason: 'Video expansion may consume paid credits and requires explicit approval.',
    },
    timeoutMs: 30000,
    retryPolicy: DEFAULT_WRITE_RETRY_POLICY,
    inputSchema: {
      type: 'object',
      properties: {
        video_uri: { type: 'string', minLength: 1 },
        target_aspect_ratio: { type: 'string' },
        prompt_text: { type: 'string', maxLength: 5000 },
      },
      required: ['video_uri','target_aspect_ratio'],
      additionalProperties: false,
    },
    outputSchema: {
      type: 'object',
      properties: {
        taskId: { type: 'string' },
        status: { type: 'string' },
        kind: { type: 'string' },
      },
      required: ['taskId','status','kind'],
    },
    enabled: true,
  },
  {
    id: 'media.avatar_video.generate',
    name: 'Generate Avatar Video',
    description: 'Generate a speaking avatar video from text or an existing audio track.',
    version: '1.0.0',
    category: 'media',
    permissions: externalPermissions,
    approvalPolicy: {
      ...DEFAULT_EXTERNAL_APPROVAL,
      reason: 'Avatar video generation may consume paid credits and requires explicit approval.',
    },
    timeoutMs: 30000,
    retryPolicy: DEFAULT_WRITE_RETRY_POLICY,
    inputSchema: {
      type: 'object',
      properties: {
        avatar_type: { type: 'string' },
        avatar_preset: { type: 'string' },
        avatar_id: { type: 'string' },
        speech_type: { type: 'string' },
        text: { type: 'string', maxLength: 10000 },
        audio_url: { type: 'string' },
        voice_preset: { type: 'string' },
      },
      required: ['avatar_type','speech_type'],
      additionalProperties: false,
    },
    outputSchema: {
      type: 'object',
      properties: {
        taskId: { type: 'string' },
        status: { type: 'string' },
        kind: { type: 'string' },
      },
      required: ['taskId','status','kind'],
    },
    enabled: true,
  },
  {
    id: 'media.video.extend',
    name: 'Extend Video',
    description: 'Continue an existing video with newly generated footage.',
    version: '1.0.0',
    category: 'media',
    permissions: externalPermissions,
    approvalPolicy: {
      ...DEFAULT_EXTERNAL_APPROVAL,
      reason: 'Video extension may consume paid credits and requires explicit approval.',
    },
    timeoutMs: 30000,
    retryPolicy: DEFAULT_WRITE_RETRY_POLICY,
    inputSchema: {
      type: 'object',
      properties: {
        prompt_video: { type: 'string', minLength: 1 },
        prompt_text: { type: 'string', minLength: 1, maxLength: 15000 },
        duration: { type: 'number', minimum: 4, maximum: 30 },
        audio: { type: 'boolean' },
      },
      required: ['prompt_video','prompt_text'],
      additionalProperties: false,
    },
    outputSchema: {
      type: 'object',
      properties: {
        taskId: { type: 'string' },
        status: { type: 'string' },
        kind: { type: 'string' },
      },
      required: ['taskId','status','kind'],
    },
    enabled: true,
  },
  {
    id: 'media.motion_transfer.generate',
    name: 'Motion Transfer',
    description: 'Use an existing video as motion guidance for a newly generated result.',
    version: '1.0.0',
    category: 'media',
    permissions: externalPermissions,
    approvalPolicy: {
      ...DEFAULT_EXTERNAL_APPROVAL,
      reason: 'Motion transfer may consume paid credits and requires explicit approval.',
    },
    timeoutMs: 30000,
    retryPolicy: DEFAULT_WRITE_RETRY_POLICY,
    inputSchema: {
      type: 'object',
      properties: {
        prompt_video: { type: 'string', minLength: 1 },
        prompt_text: { type: 'string', minLength: 1, maxLength: 15000 },
        reference_image: { type: 'string' },
        duration: { type: 'number', minimum: 4, maximum: 30 },
        ratio: { type: 'string' },
        audio: { type: 'boolean' },
      },
      required: ['prompt_video','prompt_text'],
      additionalProperties: false,
    },
    outputSchema: {
      type: 'object',
      properties: {
        taskId: { type: 'string' },
        status: { type: 'string' },
        kind: { type: 'string' },
      },
      required: ['taskId','status','kind'],
    },
    enabled: true,
  },
  {
    id: 'media.runway.status',
    name: 'Media Task Status',
    description: 'Check a video or image generation task and return finished asset URLs when available.',
    version: '1.0.0',
    category: 'media',
    permissions: externalPermissions,
    approvalPolicy: DEFAULT_READ_APPROVAL,
    timeoutMs: 20_000,
    retryPolicy: DEFAULT_READ_RETRY_POLICY,
    inputSchema: {
      type: 'object',
      properties: { task_id: { type: 'string', minLength: 1 } },
      required: ['task_id'],
      additionalProperties: false,
    },
    outputSchema: {
      type: 'object',
      properties: {
        taskId: { type: 'string' },
        status: { type: 'string' },
        assetUrls: { type: 'array' },
        ephemeral: { type: 'boolean' },
      },
      required: ['taskId', 'status', 'assetUrls', 'ephemeral'],
    },
    enabled: true,
  },
  {
    id: 'media.voice.list',
    name: 'List Voices',
    description: 'List available speech voices without exposing API credentials.',
    version: '1.0.0',
    category: 'media',
    permissions: externalPermissions,
    approvalPolicy: DEFAULT_READ_APPROVAL,
    timeoutMs: 20_000,
    retryPolicy: DEFAULT_READ_RETRY_POLICY,
    inputSchema: {
      type: 'object',
      properties: {
        search: { type: 'string', maxLength: 100 },
        limit: { type: 'number', minimum: 1, maximum: 30 },
      },
      additionalProperties: false,
    },
    outputSchema: {
      type: 'object',
      properties: {
        voices: { type: 'array' },
        count: { type: 'number' },
      },
      required: ['voices', 'count'],
    },
    enabled: true,
  },
  {
    id: 'media.voice.generate',
    name: 'Generate Voice',
    description: 'Start a paid speech generation job from text and a selected voice.',
    version: '1.0.0',
    category: 'media',
    permissions: externalPermissions,
    approvalPolicy: {
      ...DEFAULT_EXTERNAL_APPROVAL,
      reason: 'Speech generation is billed per character and requires explicit approval.',
    },
    timeoutMs: 30_000,
    retryPolicy: DEFAULT_WRITE_RETRY_POLICY,
    inputSchema: {
      type: 'object',
      properties: {
        text: { type: 'string', minLength: 1, maxLength: 20000 },
        voice_id: { type: 'string', minLength: 1 },
        model_id: { type: 'string' },
      },
      required: ['text', 'voice_id'],
      additionalProperties: false,
    },
    outputSchema: {
      type: 'object',
      properties: {
        generationId: { type: 'string' },
        status: { type: 'string' },
        kind: { type: 'string' },
      },
      required: ['generationId', 'status', 'kind'],
    },
    enabled: true,
  },
  {
    id: 'media.voice.status',
    name: 'Voice Task Status',
    description: 'Check a speech generation job and return its output URL when completed.',
    version: '1.0.0',
    category: 'media',
    permissions: externalPermissions,
    approvalPolicy: DEFAULT_READ_APPROVAL,
    timeoutMs: 20_000,
    retryPolicy: DEFAULT_READ_RETRY_POLICY,
    inputSchema: {
      type: 'object',
      properties: { generation_id: { type: 'string', minLength: 1 } },
      required: ['generation_id'],
      additionalProperties: false,
    },
    outputSchema: {
      type: 'object',
      properties: {
        generationId: { type: 'string' },
        status: { type: 'string' },
        outputUrl: { type: ['string', 'null'] },
      },
      required: ['generationId', 'status'],
    },
    enabled: true,
  },
];
