import type { RegisteredToolInput } from '@/services/runtime/tools/tool-types';
import {
  DEFAULT_READ_APPROVAL,
  DEFAULT_READ_RETRY_POLICY,
} from '@/services/runtime/tools/tool-types';

export const systemTools: RegisteredToolInput[] = [
  {
    id: 'runtime.info',
    name: 'Runtime Info',
    description: 'Return runtime metadata for the current agent execution.',
    version: '1.0.0',
    category: 'system',
    permissions: {
      requiredFlags: [],
      categoryDefault: true,
    },
    approvalPolicy: DEFAULT_READ_APPROVAL,
    timeoutMs: 5_000,
    retryPolicy: DEFAULT_READ_RETRY_POLICY,
    inputSchema: {
      type: 'object',
      properties: {},
      additionalProperties: false,
    },
    outputSchema: {
      type: 'object',
      properties: {
        runtimeVersion: { type: 'string' },
        runId: { type: 'string' },
        employeeId: { type: 'string' },
      },
      required: ['runtimeVersion', 'runId', 'employeeId'],
    },
    enabled: true,
  },
  {
    id: 'memory.search',
    name: 'Memory Search',
    description: 'Search persisted memory facts for the current organization.',
    version: '1.0.0',
    category: 'system',
    permissions: { requiredFlags: [], categoryDefault: true },
    approvalPolicy: DEFAULT_READ_APPROVAL,
    timeoutMs: 15_000,
    retryPolicy: DEFAULT_READ_RETRY_POLICY,
    inputSchema: {
      type: 'object',
      properties: {
        query: { type: 'string', minLength: 1, maxLength: 500 },
        limit: { type: 'integer', minimum: 1, maximum: 20 },
      },
      required: ['query'],
      additionalProperties: false,
    },
    outputSchema: {
      type: 'object',
      properties: { facts: { type: 'array' }, count: { type: 'integer' } },
      required: ['facts', 'count'],
    },
    enabled: true,
  },
  {
    id: 'gateway.health',
    name: 'Gateway Health',
    description: 'Check health of all configured AI gateway providers.',
    version: '1.0.0',
    category: 'system',
    permissions: { requiredFlags: [], categoryDefault: true },
    approvalPolicy: DEFAULT_READ_APPROVAL,
    timeoutMs: 15_000,
    retryPolicy: DEFAULT_READ_RETRY_POLICY,
    inputSchema: { type: 'object', properties: {}, additionalProperties: false },
    outputSchema: {
      type: 'object',
      properties: { ok: { type: 'boolean' }, providers: { type: 'array' } },
      required: ['ok', 'providers'],
    },
    enabled: true,
  },
  {
    id: 'gateway.models',
    name: 'Gateway Models',
    description: 'List models available through the gateway capabilities registry.',
    version: '1.0.0',
    category: 'system',
    permissions: { requiredFlags: [], categoryDefault: true },
    approvalPolicy: DEFAULT_READ_APPROVAL,
    timeoutMs: 10_000,
    retryPolicy: DEFAULT_READ_RETRY_POLICY,
    inputSchema: { type: 'object', properties: {}, additionalProperties: false },
    outputSchema: {
      type: 'object',
      properties: { models: { type: 'array' }, count: { type: 'integer' } },
      required: ['models', 'count'],
    },
    enabled: true,
  },
  {
    id: 'health.check',
    name: 'Health Check',
    description: 'Run a platform health check for runtime components.',
    version: '1.0.0',
    category: 'system',
    permissions: { requiredFlags: [], categoryDefault: true },
    approvalPolicy: DEFAULT_READ_APPROVAL,
    timeoutMs: 10_000,
    retryPolicy: DEFAULT_READ_RETRY_POLICY,
    inputSchema: { type: 'object', properties: {}, additionalProperties: false },
    outputSchema: {
      type: 'object',
      properties: {
        status: { type: 'string' },
        checkedAt: { type: 'string' },
        components: { type: 'object' },
      },
      required: ['status', 'checkedAt', 'components'],
    },
    enabled: true,
  },
  {
    id: 'diagnostics.runtime',
    name: 'Runtime Diagnostics',
    description: 'Return runtime execution diagnostics for the current organization.',
    version: '1.0.0',
    category: 'system',
    permissions: { requiredFlags: [], categoryDefault: true },
    approvalPolicy: DEFAULT_READ_APPROVAL,
    timeoutMs: 10_000,
    retryPolicy: DEFAULT_READ_RETRY_POLICY,
    inputSchema: { type: 'object', properties: {}, additionalProperties: false },
    outputSchema: {
      type: 'object',
      properties: {
        organizationId: { type: 'string' },
        runId: { type: 'string' },
        executionHistoryCount: { type: 'integer' },
        recentExecutions: { type: 'array' },
      },
      required: ['organizationId', 'runId', 'executionHistoryCount', 'recentExecutions'],
    },
    enabled: true,
  },
  {
    id: 'automation.status',
    name: 'Automation Status',
    description: 'Return autonomous automation worker readiness for the current run.',
    version: '1.0.0',
    category: 'system',
    permissions: { requiredFlags: [], categoryDefault: true },
    approvalPolicy: DEFAULT_READ_APPROVAL,
    timeoutMs: 5_000,
    retryPolicy: DEFAULT_READ_RETRY_POLICY,
    inputSchema: { type: 'object', properties: {}, additionalProperties: false },
    outputSchema: {
      type: 'object',
      properties: {
        runId: { type: 'string' },
        organizationId: { type: 'string' },
        automationReady: { type: 'boolean' },
        message: { type: 'string' },
      },
      required: ['runId', 'organizationId', 'automationReady', 'message'],
    },
    enabled: true,
  },
];
